package cn.nevertiree.business.user.userRegister;

public class RegisterVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userSecurity.no
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userSecurity.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userSecurity.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userSecurity.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userSecurity.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userSecurity
     *
     * @mbggenerated
     */
    public RegisterVO(String no, String name, String pwd, String token, String ip) {
        this.no = no;
        this.name = name;
        this.pwd = pwd;
        this.token = token;
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userSecurity.no
     *
     * @return the value of userSecurity.no
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userSecurity.name
     *
     * @return the value of userSecurity.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userSecurity.pwd
     *
     * @return the value of userSecurity.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userSecurity.token
     *
     * @return the value of userSecurity.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userSecurity.ip
     *
     * @return the value of userSecurity.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }
}