package cn.nevertiree.domain;

public class Chinamap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.no
     *
     * @mbggenerated
     */
    private Integer no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.parentid
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.shortname
     *
     * @mbggenerated
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.areacode
     *
     * @mbggenerated
     */
    private Integer areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.zipcode
     *
     * @mbggenerated
     */
    private Integer zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.pinyin
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.lng
     *
     * @mbggenerated
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.lat
     *
     * @mbggenerated
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.level
     *
     * @mbggenerated
     */
    private Boolean level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaMap.sort
     *
     * @mbggenerated
     */
    private Byte sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaMap
     *
     * @mbggenerated
     */
    public Chinamap(Integer no, String name, Integer parentid, String shortname, Integer areacode, Integer zipcode, String pinyin, String lng, String lat, Boolean level, String position, Byte sort) {
        this.no = no;
        this.name = name;
        this.parentid = parentid;
        this.shortname = shortname;
        this.areacode = areacode;
        this.zipcode = zipcode;
        this.pinyin = pinyin;
        this.lng = lng;
        this.lat = lat;
        this.level = level;
        this.position = position;
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.no
     *
     * @return the value of chinaMap.no
     *
     * @mbggenerated
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.name
     *
     * @return the value of chinaMap.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.parentid
     *
     * @return the value of chinaMap.parentid
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.shortname
     *
     * @return the value of chinaMap.shortname
     *
     * @mbggenerated
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.areacode
     *
     * @return the value of chinaMap.areacode
     *
     * @mbggenerated
     */
    public Integer getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.zipcode
     *
     * @return the value of chinaMap.zipcode
     *
     * @mbggenerated
     */
    public Integer getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.pinyin
     *
     * @return the value of chinaMap.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.lng
     *
     * @return the value of chinaMap.lng
     *
     * @mbggenerated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.lat
     *
     * @return the value of chinaMap.lat
     *
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.level
     *
     * @return the value of chinaMap.level
     *
     * @mbggenerated
     */
    public Boolean getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.position
     *
     * @return the value of chinaMap.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaMap.sort
     *
     * @return the value of chinaMap.sort
     *
     * @mbggenerated
     */
    public Byte getSort() {
        return sort;
    }
}