package cn.nevertiree.domain;

public class Userpersoninfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userPersonInfo.no
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userPersonInfo.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userPersonInfo.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    public Userpersoninfo(String no, String picture, String introduction) {
        this.no = no;
        this.picture = picture;
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userPersonInfo.no
     *
     * @return the value of userPersonInfo.no
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userPersonInfo.picture
     *
     * @return the value of userPersonInfo.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userPersonInfo.introduction
     *
     * @return the value of userPersonInfo.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }
}