package cn.nevertiree.domain;

public class Usersite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userSite.no
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userSite.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userSite.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userSite.county
     *
     * @mbggenerated
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userSite.district
     *
     * @mbggenerated
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userSite.street
     *
     * @mbggenerated
     */
    private String street;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userSite
     *
     * @mbggenerated
     */
    public Usersite(String no, String province, String city, String county, String district, String street) {
        this.no = no;
        this.province = province;
        this.city = city;
        this.county = county;
        this.district = district;
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userSite.no
     *
     * @return the value of userSite.no
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userSite.province
     *
     * @return the value of userSite.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userSite.city
     *
     * @return the value of userSite.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userSite.county
     *
     * @return the value of userSite.county
     *
     * @mbggenerated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userSite.district
     *
     * @return the value of userSite.district
     *
     * @mbggenerated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userSite.street
     *
     * @return the value of userSite.street
     *
     * @mbggenerated
     */
    public String getStreet() {
        return street;
    }
}