package cn.nevertiree.business.dao;

import cn.nevertiree.domain.Chinamap;
import org.apache.ibatis.annotations.*;

public interface ChinamapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaMap
     *
     * @mbggenerated
     */
    @Delete({
        "delete from chinaMap",
        "where no = #{no,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaMap
     *
     * @mbggenerated
     */
    @Insert({
        "insert into chinaMap (no, name, ",
        "parentid, shortname, ",
        "areacode, zipcode, ",
        "pinyin, lng, lat, ",
        "level, position, sort)",
        "values (#{no,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{parentid,jdbcType=INTEGER}, #{shortname,jdbcType=VARCHAR}, ",
        "#{areacode,jdbcType=INTEGER}, #{zipcode,jdbcType=INTEGER}, ",
        "#{pinyin,jdbcType=VARCHAR}, #{lng,jdbcType=VARCHAR}, #{lat,jdbcType=VARCHAR}, ",
        "#{level,jdbcType=BIT}, #{position,jdbcType=VARCHAR}, #{sort,jdbcType=TINYINT})"
    })
    int insert(Chinamap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaMap
     *
     * @mbggenerated
     */
    int insertSelective(Chinamap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaMap
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "no, name, parentid, shortname, areacode, zipcode, pinyin, lng, lat, level, position, ",
        "sort",
        "from chinaMap",
        "where no = #{no,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Chinamap selectByPrimaryKey(Integer no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaMap
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Chinamap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaMap
     *
     * @mbggenerated
     */
    @Update({
        "update chinaMap",
        "set name = #{name,jdbcType=VARCHAR},",
          "parentid = #{parentid,jdbcType=INTEGER},",
          "shortname = #{shortname,jdbcType=VARCHAR},",
          "areacode = #{areacode,jdbcType=INTEGER},",
          "zipcode = #{zipcode,jdbcType=INTEGER},",
          "pinyin = #{pinyin,jdbcType=VARCHAR},",
          "lng = #{lng,jdbcType=VARCHAR},",
          "lat = #{lat,jdbcType=VARCHAR},",
          "level = #{level,jdbcType=BIT},",
          "position = #{position,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=TINYINT}",
        "where no = #{no,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Chinamap record);
}