package cn.nevertiree.business.dao;

import cn.nevertiree.business.user.userSetting.dvo.*;
import cn.nevertiree.domain.Userpersoninfo;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.sql.Timestamp;

@Component
public interface UserpersoninfoMapper {

    /*******new method begin ************/

    /**获取或者修改名字*/
    @Select({
            "select name",
            "from userPersonInfo",
            "where no =#{0}"
    })
    String getName(String no);

    @Update({
            "update userPersonInfo",
            "set name = #{name,jdbcType=VARCHAR},",
            "where no = #{no,jdbcType=CHAR}"
    })
    int setName(UserNameVO userNameVO);

    /**获取或者修改性别*/
    @Select({
            "select gender",
            "from userPersonInfo",
            "where no =#{0}"
    })
    String getGender(String no);

    @Update({
            "update userPersonInfo",
            "set gender = #{gender,jdbcType=SET},",
            "where no = #{no,jdbcType=CHAR}"
    })
    int setGender(UserGenderVO userGenderVO);

    /**获取或者修改生日*/
    @Select({
            "select gender",
            "from userPersonInfo",
            "where no =#{0}"
    })
    Timestamp getBirth(String no);

    @Update({
            "update userPersonInfo",
            "set birth = #{birth,jdbcType=DATETIME},",
            "where no = #{no,jdbcType=CHAR}"
    })
    int setBirth(UserBirthVO userBirthVO);

    /**获取或者修改手机号*/
    @Select({
            "select mobile",
            "from userPersonInfo",
            "where no =#{0}"
    })
    int  getMobile(String no);

    @Update({
            "update userPersonInfo",
            "set mobile = #{mobile,jdbcType=INT},",
            "where no = #{no,jdbcType=CHAR}"
    })
    int setMobile(UserMobileVO userMobileVO);

    /**获取或者修改邮箱*/
    @Select({
            "select email",
            "from userPersonInfo",
            "where no =#{0}"
    })
    String getEmail(String no);

    @Update({
            "update userPersonInfo",
            "set email = #{email,jdbcType=VARCHAR},",
            "where no = #{no,jdbcType=CHAR}"
    })
    int setEmail(UserEmailVO userEmailVO);

    /**获取或者修改照片*/
    @Select({
            "select portrait",
            "from userPersonInfo",
            "where no =#{0}"
    })
    String getPortrait(String no);

    @Select({
            "select introduction",
            "from userPersonInfo",
            "where no =#{0}"
    })
    String getIntroduction(String no);

    @Update({
            "update userPersonInfo",
            "set name = #{name,jdbcType=VARCHAR},",
            "where no = #{no,jdbcType=CHAR}"
    })
    int setPortrait(UserPortraitVO userPortraitVO);

    @Update({
            "update userPersonInfo",
            "set name = #{name,jdbcType=VARCHAR},",
            "where no = #{no,jdbcType=CHAR}"
    })
    int setIntroduction(UserIntroductionVO userIntroductionVO);

    //创建新用户
    @Insert({
            "insert into userPersonInfo (no,name,email)",
            "values(#{0},#{1},#{2})"
    })
    int createUser(String no,String name,String loginName);

    //根据用户no查询用户存储picture的地址
    @Select({
            "select picture ",
            "from userPersonInfo",
            "where no = #{0}"
    })
    @ResultType(String.class)
    String getPicturePath(String no);

    //根据用户no查询用户存储introduction的地址
    @Select({
            "select introduction",
            "from userPersonInfo",
            "where no = #{0}"
    })
    @ResultType(String.class)
    String getIntroductionPath(String no);

    /*****************New Method End******************************/



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    @Delete({
        "delete from userPersonInfo",
        "where no = #{no,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into userPersonInfo (no, name, gender, ",
        "birth, mobile, ",
        "email, portrait, ",
        "introduction, registerTime)",
        "values (#{no,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, #{gender,jdbcType=CHAR}, ",
        "#{birth,jdbcType=TIMESTAMP}, #{mobile,jdbcType=INTEGER}, ",
        "#{email,jdbcType=VARCHAR}, #{portrait,jdbcType=VARCHAR}, ",
        "#{introduction,jdbcType=VARCHAR}, #{registertime,jdbcType=TIMESTAMP})"
    })
    int insert(Userpersoninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    int insertSelective(Userpersoninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "no, name, gender, birth, mobile, email, portrait, introduction, registerTime",
        "from userPersonInfo",
        "where no = #{no,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    Userpersoninfo selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userpersoninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    @Update({
        "update userPersonInfo",
        "set name = #{name,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=CHAR},",
          "birth = #{birth,jdbcType=TIMESTAMP},",
          "mobile = #{mobile,jdbcType=INTEGER},",
          "email = #{email,jdbcType=VARCHAR},",
          "portrait = #{portrait,jdbcType=VARCHAR},",
          "introduction = #{introduction,jdbcType=VARCHAR},",
          "registerTime = #{registertime,jdbcType=TIMESTAMP}",
        "where no = #{no,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(Userpersoninfo record);
}