package cn.nevertiree.business.dao;

import cn.nevertiree.domain.Userbaseinfo;
import org.apache.ibatis.annotations.*;

public interface UserbaseinfoMapper {

    /*******new method begin ************/

    @Insert({
            "insert into UserBaseInfo (no)",
            "values( #{0} )"
    })
    int createUser(String no);

    /*******new method end************/


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userBaseInfo
     *
     * @mbggenerated
     */
    @Delete({
        "delete from userBaseInfo",
        "where no = #{no,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userBaseInfo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into userBaseInfo (no, name, ",
        "gender, birth, mobile, ",
        "registerTime)",
        "values (#{no,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{gender,jdbcType=CHAR}, #{birth,jdbcType=TIMESTAMP}, #{mobile,jdbcType=INTEGER}, ",
        "#{registertime,jdbcType=TIMESTAMP})"
    })
    int insert(Userbaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userBaseInfo
     *
     * @mbggenerated
     */
    int insertSelective(Userbaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userBaseInfo
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "no, name, gender, birth, mobile, registerTime",
        "from userBaseInfo",
        "where no = #{no,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Userbaseinfo selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userBaseInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userbaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userBaseInfo
     *
     * @mbggenerated
     */
    @Update({
        "update userBaseInfo",
        "set name = #{name,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=CHAR},",
          "birth = #{birth,jdbcType=TIMESTAMP},",
          "mobile = #{mobile,jdbcType=INTEGER},",
          "registerTime = #{registertime,jdbcType=TIMESTAMP}",
        "where no = #{no,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Userbaseinfo record);
}