package cn.nevertiree.business.dao;

import cn.nevertiree.domain.Userpersoninfo;
import org.apache.ibatis.annotations.*;

public interface UserpersoninfoMapper {

    /*******new method begin ************/

    @Insert({
            "insert into UserBaseInfo (no)",
            "values( #{0} )"
    })
    int createUser(String no);


    //根据用户no查询用户存储picture的地址
    @Select({
            "select picture ",
            "from userPersonInfo",
            "where no = #{0}"
    })
    @ResultType(String.class)
    String getPicturePath(String no);

    //根据用户no查询用户存储introduction的地址
    @Select({
            "select introduction",
            "from userPersonInfo",
            "where no = #{0}"
    })
    @ResultType(String.class)
    String getIntroductionPath(String no);

    /*****************New Method End******************************/



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    @Delete({
        "delete from userPersonInfo",
        "where no = #{no,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into userPersonInfo (no, name, gender, ",
        "birth, mobile, ",
        "email, portrait, ",
        "introduction, registerTime)",
        "values (#{no,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, #{gender,jdbcType=CHAR}, ",
        "#{birth,jdbcType=TIMESTAMP}, #{mobile,jdbcType=INTEGER}, ",
        "#{email,jdbcType=VARCHAR}, #{portrait,jdbcType=VARCHAR}, ",
        "#{introduction,jdbcType=VARCHAR}, #{registertime,jdbcType=TIMESTAMP})"
    })
    int insert(Userpersoninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    int insertSelective(Userpersoninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "no, name, gender, birth, mobile, email, portrait, introduction, registerTime",
        "from userPersonInfo",
        "where no = #{no,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    Userpersoninfo selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userpersoninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userPersonInfo
     *
     * @mbggenerated
     */
    @Update({
        "update userPersonInfo",
        "set name = #{name,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=CHAR},",
          "birth = #{birth,jdbcType=TIMESTAMP},",
          "mobile = #{mobile,jdbcType=INTEGER},",
          "email = #{email,jdbcType=VARCHAR},",
          "portrait = #{portrait,jdbcType=VARCHAR},",
          "introduction = #{introduction,jdbcType=VARCHAR},",
          "registerTime = #{registertime,jdbcType=TIMESTAMP}",
        "where no = #{no,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(Userpersoninfo record);
}