package cn.nevertiree.business.dao;

import cn.nevertiree.domain.Cartbase;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Service;

@Service
public interface CartbaseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartbase
     *
     * @mbg.generated
     */
    @Delete({
        "delete from cartbase",
        "where no = #{no,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartbase
     *
     * @mbg.generated
     */
    @Insert({
        "replace into cartbase (no, cartDetail)",
        "values (#{no,jdbcType=CHAR}, #{cartdetail,jdbcType=LONGVARCHAR})"
    })
    int insert(Cartbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartbase
     *
     * @mbg.generated
     */
    int insertSelective(Cartbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartbase
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "no, cartDetail",
        "from cartbase",
        "where no = #{no,jdbcType=CHAR}"
    })
    @ResultMap("cn.nevertiree.business.dao.CartbaseMapper.ResultMapWithBLOBs")
    Cartbase selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartbase
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Cartbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartbase
     *
     * @mbg.generated
     */
    @Update({
        "update cartbase",
        "set cartDetail = #{cartdetail,jdbcType=LONGVARCHAR}",
        "where no = #{no,jdbcType=CHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(Cartbase record);
}