package cn.nevertiree.business.dao;

import cn.nevertiree.domain.Orderinfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OrderinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    @Delete({
        "delete from orderinfo",
        "where no = #{no,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    @Insert({
        "insert into orderinfo (no, bno, bname, ",
        "sno, sname, sum, ",
        "status, ordertime, ",
        "logisticsno, orderdetail)",
        "values (#{no,jdbcType=CHAR}, #{bno,jdbcType=CHAR}, #{bname,jdbcType=VARCHAR}, ",
        "#{sno,jdbcType=CHAR}, #{sname,jdbcType=VARCHAR}, #{sum,jdbcType=DECIMAL}, ",
        "#{status,jdbcType=CHAR}, #{ordertime,jdbcType=TIMESTAMP}, ",
        "#{logisticsno,jdbcType=CHAR}, #{orderdetail,jdbcType=LONGVARCHAR})"
    })
    int insert(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int insertSelective(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "no, bno, bname, sno, sname, sum, status, ordertime, logisticsno, orderdetail",
        "from orderinfo",
        "where no = #{no,jdbcType=CHAR}"
    })
    @ResultMap("cn.nevertiree.business.dao.OrderinfoMapper.ResultMapWithBLOBs")
    Orderinfo selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    @Update({
        "update orderinfo",
        "set bno = #{bno,jdbcType=CHAR},",
          "bname = #{bname,jdbcType=VARCHAR},",
          "sno = #{sno,jdbcType=CHAR},",
          "sname = #{sname,jdbcType=VARCHAR},",
          "sum = #{sum,jdbcType=DECIMAL},",
          "status = #{status,jdbcType=CHAR},",
          "ordertime = #{ordertime,jdbcType=TIMESTAMP},",
          "logisticsno = #{logisticsno,jdbcType=CHAR},",
          "orderdetail = #{orderdetail,jdbcType=LONGVARCHAR}",
        "where no = #{no,jdbcType=CHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    @Update({
        "update orderinfo",
        "set bno = #{bno,jdbcType=CHAR},",
          "bname = #{bname,jdbcType=VARCHAR},",
          "sno = #{sno,jdbcType=CHAR},",
          "sname = #{sname,jdbcType=VARCHAR},",
          "sum = #{sum,jdbcType=DECIMAL},",
          "status = #{status,jdbcType=CHAR},",
          "ordertime = #{ordertime,jdbcType=TIMESTAMP},",
          "logisticsno = #{logisticsno,jdbcType=CHAR}",
        "where no = #{no,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(Orderinfo record);
}