package cn.nevertiree.business.dao;

import cn.nevertiree.domain.Productbase;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;

@Component
public interface ProductbaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbase
     *
     * @mbg.generated
     */
    @Delete({
        "delete from productbase",
        "where no = #{no,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbase
     *
     * @mbg.generated
     */
    @Insert({
        "insert into productbase (no, name, sellerNo, ",
        "sellerName, quantity, ",
        "price, catalog, ",
        "picture, introduction, ",
        "releaseTime)",
        "values (#{no,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, #{sellerno,jdbcType=CHAR}, ",
        "#{sellername,jdbcType=VARCHAR}, #{quantity,jdbcType=INTEGER}, ",
        "#{price,jdbcType=DECIMAL}, #{catalog,jdbcType=VARCHAR}, ",
        "#{picture,jdbcType=VARCHAR}, #{introduction,jdbcType=VARCHAR}, ",
        "#{releasetime,jdbcType=TIMESTAMP})"
    })
    int insert(Productbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbase
     *
     * @mbg.generated
     */
    int insertSelective(Productbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbase
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "no, name, sellerNo, sellerName, quantity, price, catalog, picture, introduction, ",
        "releaseTime",
        "from productbase",
        "where no = #{no,jdbcType=CHAR}"
    })
    @ResultMap("cn.nevertiree.business.dao.ProductbaseMapper.BaseResultMap")
    Productbase selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbase
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Productbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbase
     *
     * @mbg.generated
     */
    @Update({
        "update productbase",
        "set name = #{name,jdbcType=VARCHAR},",
          "sellerNo = #{sellerno,jdbcType=CHAR},",
          "sellerName = #{sellername,jdbcType=VARCHAR},",
          "quantity = #{quantity,jdbcType=INTEGER},",
          "price = #{price,jdbcType=DECIMAL},",
          "catalog = #{catalog,jdbcType=VARCHAR},",
          "picture = #{picture,jdbcType=VARCHAR},",
          "introduction = #{introduction,jdbcType=VARCHAR},",
          "releaseTime = #{releasetime,jdbcType=TIMESTAMP}",
        "where no = #{no,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(Productbase record);
}