package cn.nevertiree.business.dao;

import cn.nevertiree.domain.Userinfo;
import org.apache.ibatis.annotations.*;

public interface UserinfoMapper {
    /*********new method begin******/

    @Select({
            "select count(*)",
            "from userInfo",
            "where name = {0}",
            "and pwd = {1}"
    })
    @ResultType(Integer.class)
    int loginByPwd(String name, String pwd);


    /*********new method end******/


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    @Delete({
        "delete from userInfo",
        "where no = #{no,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into userInfo (no, name, ",
        "pwd)",
        "values (#{no,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{pwd,jdbcType=VARCHAR})"
    })
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "no, name, pwd",
        "from userInfo",
        "where no = #{no,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Userinfo selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    @Update({
        "update userInfo",
        "set name = #{name,jdbcType=VARCHAR},",
          "pwd = #{pwd,jdbcType=VARCHAR}",
        "where no = #{no,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Userinfo record);
}