package cn.nevertiree.business.dvo;

import java.util.Date;

public class UserBaseInfoVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userBaseInfo.no
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userBaseInfo.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userBaseInfo.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userBaseInfo.birth
     *
     * @mbggenerated
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userBaseInfo.mobile
     *
     * @mbggenerated
     */
    private Integer mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userBaseInfo.registerTime
     *
     * @mbggenerated
     */
    private Date registertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userBaseInfo
     *
     * @mbggenerated
     */
    public UserBaseInfoVO(String no, String name, String gender, Date birth, Integer mobile, Date registertime) {
        this.no = no;
        this.name = name;
        this.gender = gender;
        this.birth = birth;
        this.mobile = mobile;
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userBaseInfo.no
     *
     * @return the value of userBaseInfo.no
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userBaseInfo.name
     *
     * @return the value of userBaseInfo.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userBaseInfo.gender
     *
     * @return the value of userBaseInfo.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userBaseInfo.birth
     *
     * @return the value of userBaseInfo.birth
     *
     * @mbggenerated
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userBaseInfo.mobile
     *
     * @return the value of userBaseInfo.mobile
     *
     * @mbggenerated
     */
    public Integer getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userBaseInfo.registerTime
     *
     * @return the value of userBaseInfo.registerTime
     *
     * @mbggenerated
     */
    public Date getRegistertime() {
        return registertime;
    }
}