package cn.nevertiree.domain;

public class Cartbase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartbase.no
     *
     * @mbg.generated
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartbase.cartDetail
     *
     * @mbg.generated
     */
    private String cartdetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartbase
     *
     * @mbg.generated
     */
    public Cartbase(String no, String cartdetail) {
        this.no = no;
        this.cartdetail = cartdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartbase.no
     *
     * @return the value of cartbase.no
     *
     * @mbg.generated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartbase.cartDetail
     *
     * @return the value of cartbase.cartDetail
     *
     * @mbg.generated
     */
    public String getCartdetail() {
        return cartdetail;
    }
}