package cn.nevertiree.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Orderinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.no
     *
     * @mbg.generated
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.bno
     *
     * @mbg.generated
     */
    private String bno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.bname
     *
     * @mbg.generated
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.sno
     *
     * @mbg.generated
     */
    private String sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.sum
     *
     * @mbg.generated
     */
    private BigDecimal sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.ordertime
     *
     * @mbg.generated
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.logisticsno
     *
     * @mbg.generated
     */
    private String logisticsno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderdetail
     *
     * @mbg.generated
     */
    private String orderdetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    public Orderinfo(String no, String bno, String bname, String sno, String sname, BigDecimal sum, String status, Date ordertime, String logisticsno, String orderdetail) {
        this.no = no;
        this.bno = bno;
        this.bname = bname;
        this.sno = sno;
        this.sname = sname;
        this.sum = sum;
        this.status = status;
        this.ordertime = ordertime;
        this.logisticsno = logisticsno;
        this.orderdetail = orderdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.no
     *
     * @return the value of orderinfo.no
     *
     * @mbg.generated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.bno
     *
     * @return the value of orderinfo.bno
     *
     * @mbg.generated
     */
    public String getBno() {
        return bno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.bname
     *
     * @return the value of orderinfo.bname
     *
     * @mbg.generated
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.sno
     *
     * @return the value of orderinfo.sno
     *
     * @mbg.generated
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.sname
     *
     * @return the value of orderinfo.sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.sum
     *
     * @return the value of orderinfo.sum
     *
     * @mbg.generated
     */
    public BigDecimal getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.status
     *
     * @return the value of orderinfo.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.ordertime
     *
     * @return the value of orderinfo.ordertime
     *
     * @mbg.generated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.logisticsno
     *
     * @return the value of orderinfo.logisticsno
     *
     * @mbg.generated
     */
    public String getLogisticsno() {
        return logisticsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderdetail
     *
     * @return the value of orderinfo.orderdetail
     *
     * @mbg.generated
     */
    public String getOrderdetail() {
        return orderdetail;
    }
}