package cn.nevertiree.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Productbase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbase.no
     *
     * @mbg.generated
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbase.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbase.sellerNo
     *
     * @mbg.generated
     */
    private String sellerno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbase.sellerName
     *
     * @mbg.generated
     */
    private String sellername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbase.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbase.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbase.catalog
     *
     * @mbg.generated
     */
    private String catalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbase.picture
     *
     * @mbg.generated
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbase.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbase.releaseTime
     *
     * @mbg.generated
     */
    private Date releasetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbase
     *
     * @mbg.generated
     */
    public Productbase(String no, String name, String sellerno, String sellername, Integer quantity, BigDecimal price, String catalog, String picture, String introduction, Date releasetime) {
        this.no = no;
        this.name = name;
        this.sellerno = sellerno;
        this.sellername = sellername;
        this.quantity = quantity;
        this.price = price;
        this.catalog = catalog;
        this.picture = picture;
        this.introduction = introduction;
        this.releasetime = releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbase.no
     *
     * @return the value of productbase.no
     *
     * @mbg.generated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbase.name
     *
     * @return the value of productbase.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbase.sellerNo
     *
     * @return the value of productbase.sellerNo
     *
     * @mbg.generated
     */
    public String getSellerno() {
        return sellerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbase.sellerName
     *
     * @return the value of productbase.sellerName
     *
     * @mbg.generated
     */
    public String getSellername() {
        return sellername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbase.quantity
     *
     * @return the value of productbase.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbase.price
     *
     * @return the value of productbase.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbase.catalog
     *
     * @return the value of productbase.catalog
     *
     * @mbg.generated
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbase.picture
     *
     * @return the value of productbase.picture
     *
     * @mbg.generated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbase.introduction
     *
     * @return the value of productbase.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbase.releaseTime
     *
     * @return the value of productbase.releaseTime
     *
     * @mbg.generated
     */
    public Date getReleasetime() {
        return releasetime;
    }
}