package cn.nevertiree.domain;

import java.util.Date;

public class Userbase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbase.no
     *
     * @mbg.generated
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbase.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbase.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbase.birth
     *
     * @mbg.generated
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbase.mobile
     *
     * @mbg.generated
     */
    private Integer mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbase.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbase.portrait
     *
     * @mbg.generated
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbase.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbase.registerTime
     *
     * @mbg.generated
     */
    private Date registertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbase
     *
     * @mbg.generated
     */
    public Userbase(String no, String name, String gender, Date birth, Integer mobile, String email, String portrait, String introduction, Date registertime) {
        this.no = no;
        this.name = name;
        this.gender = gender;
        this.birth = birth;
        this.mobile = mobile;
        this.email = email;
        this.portrait = portrait;
        this.introduction = introduction;
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbase.no
     *
     * @return the value of userbase.no
     *
     * @mbg.generated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbase.name
     *
     * @return the value of userbase.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbase.gender
     *
     * @return the value of userbase.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbase.birth
     *
     * @return the value of userbase.birth
     *
     * @mbg.generated
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbase.mobile
     *
     * @return the value of userbase.mobile
     *
     * @mbg.generated
     */
    public Integer getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbase.email
     *
     * @return the value of userbase.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbase.portrait
     *
     * @return the value of userbase.portrait
     *
     * @mbg.generated
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbase.introduction
     *
     * @return the value of userbase.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbase.registerTime
     *
     * @return the value of userbase.registerTime
     *
     * @mbg.generated
     */
    public Date getRegistertime() {
        return registertime;
    }
}